In [3]:
# sort a list without using sort function
old_list = [23,34,15,7,4,65,17,12]
new_list = []

while old_list:
    min = old_list[0]
    for i in old_list:
        if i < min:
            min = i
    new_list.append(min)
    old_list.remove(min)
           
new_list

[4, 7, 12, 15, 17, 23, 34, 65]

In [1]:
myList = [1,4,6,0,2,7,8,3,5]
target = 5
already_seen = set()
pairs = []
for x in myList:
    if (target - x) in already_seen:
        pairs.append((x, target - x))
    already_seen.add(x)
    print(already_seen)
pairs

{1}
{1, 4}
{1, 4, 6}
{0, 1, 4, 6}
{0, 1, 2, 4, 6}
{0, 1, 2, 4, 6, 7}
{0, 1, 2, 4, 6, 7, 8}
{0, 1, 2, 3, 4, 6, 7, 8}
{0, 1, 2, 3, 4, 5, 6, 7, 8}


[(4, 1), (3, 2), (5, 0)]

In [7]:
# with dictonary 
nums = [8, 7, 2, 5, 3, 1]
target = 10

d = {}
out = []

for i,e in enumerate(nums):
    if (target-e) in d:
        out.append([e,target-e])
    d[e] = i
    print(d)
out
    

{8: 0}
{8: 0, 7: 1}
{8: 0, 7: 1, 2: 2}
{8: 0, 7: 1, 2: 2, 5: 3}
{8: 0, 7: 1, 2: 2, 5: 3, 3: 4}
{8: 0, 7: 1, 2: 2, 5: 3, 3: 4, 1: 5}


[[2, 8], [3, 7]]

In [ ]:
#pandas filters(get the details of all row which coloumn has a specific value)
df[df.risk.isin(['Small','Medium','High'])]

In [2]:
#How can you initialize a 5*5 numpy array with only zeroes

import numpy as np
n1=np.zeros((5,5))
n1

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [2]:
#Find out the mean, median and standard deviation of this numpy array
n1=np.array([10,20,30,40,50,60])
print(np.mean(n1))
print(np.median(n1))
print(np.std(n1))

35.0
35.0
17.07825127659933


In [3]:
# create 1d array
# creating the list
list = [100, 200, 300, 400]
  
# creating 1-d array
n = np.array(list)
print(n)

[100 200 300 400]


In [4]:
#create 2d array
a = [[1, 2, 3], [4, 5, 6]]
nd_a = np.array(a)
nd_a

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
a_3d_array = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
a_3d_array

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])